@ECHO OFF

SET log=analyze.txt
DEL %log%

:: Download Ajax Minifier here: http://ajaxmin.codeplex.com/
SET ajaxmin="C:\Program Files (x86)\Microsoft\Microsoft Ajax Minifier\AjaxMin.exe"

:: Also checkout UglifyJS (require nodejs): https://github.com/mishoo/UglifyJS
:: Also checkout YUI Compressor: http://developer.yahoo.com/yui/compressor/

:: 1>NUL		Dismiss minification result
:: 2>>%log%		Add analysis infos to log

%ajaxmin% -analyze tab/tabs.js ^
	-global:$,Class,Element ^
	1>NUL 2>>%log%
%ajaxmin% -analyze tab/search.js ^
	-global:$,$$,$R,Class,Control,Tab,TableKit,Draggable,Element,genres,FormatTime,sort_unique ^
	1>NUL 2>>%log%%
%ajaxmin% -analyze tab/upload.js ^
	-global:$,$$,JSON,qq,Class,Tab,TableKit,MusicFieldEditor,Notifications,genres,Element ^
	1>NUL 2>>%log%%
%ajaxmin% -analyze tab/debug.js ^
	-global:$,Class,Tab,JSON ^
	1>NUL 2>>%log%%
%ajaxmin% -analyze tab/customQueries.js ^
	-global:$,Class,Tab,JSON,Notifications,Action,Query ^
	1>NUL 2>>%log%%
%ajaxmin% -analyze tab/notification.js ^
	-global:$,Element,Notifications,Class,Tab ^
	1>NUL 2>>%log%%

%ajaxmin% -analyze genres.js tools.js 1>NUL 2>>%log%
%ajaxmin% -analyze action.js -global:Extend 1>NUL 2>>%log%%
%ajaxmin% -analyze query.js -global:Action 1>NUL 2>>%log%%
%ajaxmin% -analyze notifications.js ^
	-global:$,Effect,Event ^
	1>NUL 2>>%log%%
%ajaxmin% -analyze musicFieldEditor.js ^
	-global:$,$$,Event,TableKit,UploadTab,genres,genresOrdered ^
	1>NUL 2>>%log%%
%ajaxmin% -analyze jukeboxC.js ^
	-global:Action,Query,Ajax,Extend,Notifications,JukeboxUI,Sound ^
	1>NUL 2>>%log%%
%ajaxmin% -analyze jukeboxUI.js ^
	-global:$,$$,$R,Control,Extend,Event,Element,JSON,Droppables,Draggable,Tabs,SearchTab,UploadTab,DebugTab,NotificationTab,CustomQueriesTab,FormatTime,genresOrdered ^
	1>NUL 2>>%log%%

:: Analyze the concatenated file generated by gruntjs
%ajaxmin% -analyze jukebox.js ^
	-global:JSON,Ajax,Notifications,Sound,Draggable,Droppables,$R,$,$$,Class,Control,Element,Event,TableKit,qq ^
	1>NUL 2>>%log%%

:: Analyze the CSS
%ajaxmin% -analyze ../css/style.css 1>NUL 2>>%log%%

ECHO Analysis done in %log%